# Copyright (c) 2016-2020 Martin Donath <martin.donath@squidfunk.com>
# Copyright (c) 2020 Laszlo Fogas <laszlo@laszlo.cloud>

# Permission is hereby granted, free of charge, to any person obtaining a copy
# of this software and associated documentation files (the "Software"), to
# deal in the Software without restriction, including without limitation the
# rights to use, copy, modify, merge, publish, distribute, sublicense, and/or
# sell copies of the Software, and to permit persons to whom the Software is
# furnished to do so, subject to the following conditions:

# The above copyright notice and this permission notice shall be included in
# all copies or substantial portions of the Software.

# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NON-INFRINGEMENT. IN NO EVENT SHALL THE
# AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
# LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING
# FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS
# IN THE SOFTWARE.

# Project information
site_name: OneChart
site_url: https://onechart.dev/
site_author: Laszlo Fogas
site_description: >-
  One chart to rule them all. A generic Helm chart for your application deployments. Because no-one can remember the Kubernetes yaml syntax.
# Repository
repo_name: onechart/onechart
repo_url: https://github.com/onechart/onechart
edit_uri: https://github.com/onechart/onechart/tree/master/website/docs

extra_css:
  - stylesheets/extra.css

# Copyright
copyright: Copyright &copy; 2020 Laszlo Fogas

# Configuration
theme:
  name: material
  custom_dir: overrides

  # 404 page
  static_templates:
    - 404.html

  # Don't include MkDocs' JavaScript
  include_search_page: false
  search_index_only: true

  # Default values, taken from mkdocs_theme.yml
  language: en
  features:
    - navigation.tabs
#    - navigation.instant
  palette:
    scheme: default
    primary: indigo
    accent: indigo
  font:
    text: Roboto
    code: Roboto Mono
  favicon: assets/favicon.png
  icon:
    logo: fontawesome/regular/circle

# Plugins
plugins:
  - search
  - minify:
      minify_html: true

# Customization
extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/laszlocph
    - icon: fontawesome/brands/gitter
      link: https://gitter.im/squidfunk/mkdocs-material
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/laszlocph
    - icon: fontawesome/brands/linkedin
      link: https://linkedin.com/in/laszlofogas

# Extensions
markdown_extensions:
  - admonition
  - abbr
  - attr_list
  - def_list
  - footnotes
  - meta
  - toc:
      permalink: true
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.critic
  - pymdownx.details
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - pymdownx.highlight
  - pymdownx.inlinehilite
  - pymdownx.keys
  - pymdownx.magiclink:
      repo_url_shorthand: true
      user: squidfunk
      repo: mkdocs-material
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.snippets:
      check_paths: true
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.tabbed
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde

# Page tree
nav:
  - Home: index.md
  - Getting started:
      - Getting started: getting-started.md
  - Examples:
      - Deploying an image: examples/deploying-an-image.md
      - Deploying a private image: examples/deploying-a-private-image.md
      - Environment variables: examples/environment-variables.md
      - Secrets: examples/secrets.md
      - Domain names: examples/domain-names.md
      - Volumes: examples/volumes.md
      - Custom command: examples/custom-command.md
      - Cron job: examples/cron-job.md
      - Feature branch deploys: examples/feature-branch-deploys.md
      - Prometheus monitoring rules: examples/prometheus-monitoring-rules.md
      - Debug toolbox in a sidecar: examples/debugSidecar.md
